[package]
name = "pg_signal"
version = "1.0.0"
edition = "2021"

[dependencies]
pgrx = "0.11.3"
rustfft = "6.2.0"

[dev-dependencies]
pgrx-tests = "=0.11.4"

[features]
default = ["pg15"]
pg15 = [
  "pgrx/pg15",
  "pgrx-tests/pg15"
]
pg16 = [
  "pgrx/pg16",
  "pgrx-tests/pg16"
]
pg_test = []

[lib]
crate-type = ["cdylib"]

[lints.clippy]
complexity = "deny"
correctness = "deny"
pedantic = "deny"
perf = "deny"
restriction = "deny"
style = "deny"
suspicious = "deny"

[lints.rust]
warnings = "deny"

[profile.dev]
panic = "unwind"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "unwind"
